### ISSUE TITLE
Make app registration opt-in

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint#195]
At the moment, any App instance can register other Apps:

```js
myAppInstance.registerApp(SomeOtherApp);
```

## Opt-in API example

We primarily want only Root Apps to be able to register other apps. We can do it with an API like this:

```js
import { createApp } from 'frint';

const RootApp = createApp({
  registerable: true, // by default, it will be `false`
});
```

OR, we can possibly go ahead with a decorator-like API:

```js
import { createApp, makeItRegisterable } from 'frint';

const RootApp = createApp({});

export default makeItRegisterable()(RootApp);
```

Doing so means, only those Apps we explicitly want to be able to register other Apps, will allow methods like `.registerApp()`.

**Comment by alexmiranda** [comment]
First of all, _registrable_ would be any app, but the root one, thus it doesn't make sense to use the word _registrable_ here.

Second, this distinction barely brings any benefit, does it? Because there can always be a higher order, wrapping application that provides extra features to children applications, including one that contains services and allows other apps to be registered (think of scope).

I think it makes sense to treat the root app as something as dynamic as child apps.  If you happen to register an App to be loaded within a parent one (supposedly the root), it will be available in that scope, but it should not be visible/available in a sibling App. That would IMO be the only distinction I'd make, if that's simple to do (and that's not what we are doing now).

If you want to revoke or suppress the `registerApp` from child apps, you're only trying to engross distinction between Apps, then the concept of _root_ no longer makes sense.  You could warn the users they are registering an App at a non-root level, but what would anyone gain from it?  I would not try to prevent this and it looks like you're trying to protect from yourself only (as a developer)!

So:
-  Either you admit all apps have the same API, same behaviour and can be composed however the developer prefers.  Potentially allowing developers to register apps at any level (with or without warnings).  This is more like the current API and has the benefit that is simple and does not require introducing a new concept.
- Or you would have to delegate the registration to another component (a new one), like a Composer that you can pass down from the main app (read, your root) _before you render it_. The composer would have methods that would allow regions contained in any level to query which apps are to be mounted there.  This is slightly more complicated, but has the benefit that only a single Composer is ever used in a page, because it's defined before you _mount_ the root app.

**Comment by fahad19** [comment]
wont-do.
