### ISSUE TITLE
Proposal: Make collections immutable by default in frint-data

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint#354]
## Currently

In `frint-data`, models are immutable by default. If you want any properties to be changed, you can only do it via custom defined methods:

```js
import { Types, createModel } from 'frint-data';

const Todo = createModel({
  schema: {
    title: Types.string,
  },

  setTitle(newTitle) {
    this.title = newTitle;
  }
});

const todo = new Todo({ title: 'Hello World' });

// has no impact
todo.title = 'updated title';

// can only be done via methods
todo.setTitle('Hello Universe');
```

But collections on the other hand exposes methods that can mutate its models:

```js
import { createCollection } from 'frint-data';

const Todos = createCollection({
  model: Todo,
});

const todos = new Todos([{ title: 'Hello World' }]);
todos.push(new Todo({ title: 'About us' })); 

// now `todos` has two models
```

## Expection

Like models, we also expect Collections to be immutable by default, and not allow any changes unless the class permits it. This would avoid any unpredictable behaviour in the app later.

I request for comments from everyone, like what API would be ideal to make this happen.

### 1: Mutating methods allowed inside custom methods only

```js
import { createCollection } from 'frint-data';
import Todo from '../models/Todo';

const Todos = createCollection({
  model: Todo,
  
  addTodo(todo) {
    // allow access to "write/delete" methods inside custom methods only
    this.push(todo);
  },
});
```

### 2: Additional property at class level allowing mutation

```js
import { createCollection } from 'frint-data';
import Todo from '../models/Todo';

const Todos = createCollection({
  model: Todo,

  // setting this to `true` gives access to `push` and other methods
  mutable: true,
});
```

**Comment by alexmiranda** [comment]
Let's discuss this tomorrow :-)

**Comment by jackTheRipper** [comment]
I would go for the first option in order to be consistent with the current Model implementation that we have. The possibility of mutating the model should be managed internally. It means that until you implemented your setters, the list is by default immutable. 

An extra property could be a bit confusing from my point of view.

**Comment by fahad19** [comment]
@jackTheRipper: yeah, I like the first option too myself.

**Comment by mAiNiNfEcTiOn** [comment]
I'm seeing a bunch of different concepts mixed in the PR #361:

`read-only` - By hiding attributes under the rule _it must have a method to write on it_ it makes the attributes read-only in case you have none. Which mean they are `public` getters, but `private` setters.

`immutable` - According to ImmutableJS, the definition is:

> Immutable data cannot be changed once created, leading to much simpler application development, no defensive copying, and enabling advanced memoization and change detection techniques with simple logic

which for me goes agains the concept of the private _setters_, unless they are forced to generate new immutable structures. That's not simple specially with _collections_ where - as I spoke with @fahad19 before - if you use immutable structures for a large collection that implies generating a new large collection every time you change it.

----

Now, if we look into the _schema_ I see that we're defining types for each attribute of the model. Why not extending it to:

```js
{
  schema: {
    attributeName: {
      initialValue: [Function, scalar, ...], // in case is readOnly, allow you to have a fixed value
      readOnly: [true, false], // default true, forcing the need to have a private function
      type: Types.[type], // was already there, obvious use =)
    },
}
```

* initialValue - would allow us to say that a certain attribute is `readOnly` and therefore - even if you have a setter - it is not allowed to set it (good for things like creation dates or other types of fields that should not change during execution or mutation of the remaining fields.
It can be a `Function` that, when executed, returns the initial value. E.g.:
```js
(initialModelData) => {
  return new Date.now();
}
```

* readOnly - defines if an attribute is read-only. That prevents the field from being changed. Even with a setter.

----

Now, beyond of the basic functionality above, this could bring some extra logic to the model regarding the setters. If a field is not `readOnly` it means you are allowed to change its value... If that's the case, you can verify if the field as a setter defined in the schema. E.g. `setTitle()`.
If not, the model can immediately provide a _generic_ setter that the only thing it does is just receiving the value and setting the value (after validating the value against the schema).

----

And last but not the least, I'd like to do a question regarding the usage _context_ of a model. Let's take the CRUD interfaces as an example... Normally there are things that are insertable on __C__reation that are not editable/updatable on __U__pdate. So, the schema changes based on it. How are we handling that? Because it seems that I have to have 2 different schemas for the different cases.

**Comment by fahad19** [comment]
Thanks for sharing a deeper understanding of the topics, @mAiNiNfEcTiOn!

---

### `read-only` vs immutable

What `frint-data` suggests about immutability is that Models and Collections are **immutable by default**. Meaning, they can't be mutated once created with the the library, without adding any additional methods.

Once you start adding custom methods, only then you are allowed to change values they hold. And then, you don't really have an immutable data structure any more. because as you grow your model with nested models and collections, they are accessible internally by references. Each change will not create a new updated copy of the Model or Collection.

---

## Initial value

We can handle them in two ways currently:

### Types

```js
import { Types, createModel } from 'frint-data';

const Person = createModel({
  schema: {
    name: Types.string.defaults('John Smith'), // `.defaults(val)` by chaining
  },
});
```

See more on chaining Types: https://frint.js.org/docs/packages/frint-data/#types

### `initialize` lifecycle callback

```js
import { Types, createModel } from 'frint-data';

const Person = createModel({
  schema: {
    name: Types.string,
  },

  initialize() {
    this.name = 'John Smith';
  },
});
```

See more here: https://frint.js.org/docs/packages/frint-data/#createmodel

---

## Keeping `schema` simple with expressive Types

My intention is to keep the `schema` definition as simple and expressive as possible. And don't want to add more configs there.

Currently, it is a simple check with functions.

For example, `Types.string` is a function which returns the argument it receives if everything is as expected, otherwise just throws a custom `TypesError` shipped with the package:

```js
import { Types } from 'frint-data';

Types.string('hello world'); // returns `hello world`
Types.string.defaults('foo')(undefined); // returns `foo`
Types.string(123); // throws TypesError
```

---

## CRUD based check per field

> And last but not the least, I'd like to do a question regarding the usage context of a model. Let's take the CRUD interfaces as an example... Normally there are things that are insertable on __C__reation that are not editable/updatable on __U__pdate. So, the schema changes based on it. How are we handling that? Because it seems that I have to have 2 different schemas for the different cases.

This is a very good question.

I can see a use case, where a Post is created with date, but we don't want that date to be updated later.

```js
import { Types, createModel } from 'frint-data';

const Post = createModel({
  schema: {
    title: Types.string,
    createdAt: Types.string, // we better have a datetime type soon
  },

  setTitle(title) {
    this.title = title;
  },
});
```

The schema and custom methods of a Model stay at the same place when defining the full Model. My suggestion is, if you don't want any particular field to be updated, then don't update it in any of your custom methods.

If you don't define it here, no one else can change it from anywhere else either.

**Comment by mAiNiNfEcTiOn** [comment]
Hi @fahad19 thanks for clarifying some of the points.

* Regarding the _initial value_ section, seems nice to do the `.defaults()`. 👍
* Does it mean that if I want to have a more complex _default_ I'd use the `initialize()` method, then?

Now, in the first point `read-only` vs immutable, if you want to consider the Model immutable by default, it would be interesting to think on how components do _props_ comparisons on lifecycle methods such as `shouldComponentUpdate()`, where complex structures have a complex check (deepEqual comparisons and stuff...). So, an immutable structure would allow us to do a direct comparison:

```js
shouldComponentUpdate(nextProps) {
  return (nextProps.model !== this..props.model);
}
```

Another way to see it is to track changes from within `Model`s which means you're able to create a custom method for comparisons (e.g. `isEqual()`), allowing a developer to do:

```js
shouldComponentUpdate(nextProps) {
  const { model } = this.props;
  return !model.isEqual(nextProps.model);
}
```

Where this would move the immutability to the attributes level, instead of the _Model's instance_.

Immutability solves the direct comparison on complex structures (such as Arrays, Objects), and also solve problems of changes by reference where others have access to the same structure and attempt to mutate it via mutable methods - e.g. `Array.prototype.push`, `Array.prototype.splice` - or even via change of nested properties on objects.

This is the part where if I define a `setTitle()` and run it anywhere, the Model's instance is still the same, although internally it changed.
Also, if the _title_ was an object and I'd set a prop within it, I'd probably mutate the object, but the object memory address would still be the same (therefore same object).

**Comment by fahad19** [comment]
Regarding complex structures, a particular Model is never expected to have Arrays of Objects as attributes. It should rather have a Collection or another Model.

like this for example with Embedding feature:

```js
import { Types, createModel, createCollection } from 'frint-data';

const Book = createModel({
  schema: {
    id: Types.string,
    title: Types.string,
  },
});

const Books = createCollection({
  model: Book,
});

const Address = createModel({
  schema: {
    street: Types.string,
    country: Types.string,
  },
});

const Author = createModel({
  schema: {
    id: Types.string,
    name: Types.string,
    address: Types.model.of(Address),
    books: Types.collection.of(Books),
  },
});
```

Further reading: https://frint.js.org/docs/packages/frint-data/#embedding

Can be instantiated like this:

```js
const author = new Author({
  id: '123',
  name: 'Foo',
  address: {
    street: 'blah..',
  },
  books: [
    { title: 'Bar' },
  ]
});

// author.address is an instance of Address
// author.books is an instance of Books
// author.books.at(0) is an instance of Book
```

The events are triggered on new sets (setting/changing/removing values), and also further by bubbling up the events to the parent(s). 

So a change in a particular `Book` will trigger another event in `Books`, and then to `Author`.

The comparison checks are not happening at the Model/Collection instance level anywhere.

If you do want that, I suggest doing it with RxJS operators:

```js
import { map, distinctUntilChanged } from 'rxjs/operators';

author.get$()
  .pipe(
    map(model => model.name),
    distinctUntilChanged(),
  )
  // will trigger only when the Author's name has changed to another value
  .subscribe(authorName => console.log(authorName);
```
