### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint#375]
I am considering starting a blog for this project. Initially we can post Release Notes there, but it can grow into: 

* Tutorials (even from guest authors)
* Case studies of production websites (and companies) using FrintJS
* Integration with other popular libraries
* Introducing tools popping up in the ecosystem
* Interviews with indie developers using the framework
* ...etc

Question is, should we create a new blog section under the existing https://frint.js.org website, or use Medium?

Popular projects like Webpack and Vue.js are already on Medium, but would like to hear some input from others.

**Comment by nunorfpt** [comment]
Why not both? have a new blog section and also post each article on Medium, if it makes sense to post it. For example Release Notes might be posted on the blog but not on Medium

**Comment by fahad19** [comment]
@nunorfpt: you make a good point.

We do indeed have a changelog page here on the site: https://frint.js.org/docs/changelog/

By release notes on a blog, I meant announcing the release (majors and minors).

**Comment by nunorfpt** [comment]
@fahad19 I see both channels as complementary. Beside the release notes, tutorials from guest authors might also be posted on the blog, but the author himself might want to post it on his own account on medium. A small blog post introducing some new functionality to FrintJS might not make sense on Medium until a more detailed description on how to use that functionality is written.

**Comment by markvincze** [comment]
Good question. Personally I'm quite apprehensive with Medium (and similar services), because in case of something like a blog, I would like to completely own it. (Although I don't know the licensing of Medium, but I'd assume that with Medium too you're owning the content as the writer.)

On the other hand there are big respectable companies/orgs using it, so probably you cannot go wrong with it, and it's convenient because you don't have to set up your own blogging platform, and you get commenting, google indexing, etc. out of the box.

@nunorfpt I wouldn't publish posts on two different channels, to me that seems to be really confusing, like if one of the channels was the official ones, and the other one was a copy or something, and I don't think Google is happy about that. Also, how do you handle comments?

**Comment by fahad19** [comment]
googled a bit and I found this post: https://medium.com/policy/medium-terms-of-service-9db0094a1e0f

> You own the rights to the content you create and post on Medium.

**Comment by fahad19** [comment]
Blog created here: https://medium.com/frintjs

@frintjs/core and @frintjs/maintainers: please give me your Medium.com usernames, and I will add you all there.
