### ISSUE TITLE
 Should we move to TypeScript?

### ISSUE THREAD

**Issue by fahad19** [frintjs/frint#388]
This is an issue for collecting feedback on whether writing FrintJS source in TypeScript is a good idea or not.

Some questions that I would like everyone to answer:

* Does it add value? How?
* What are the disadvantages?
* Our manually written typings are out of sync, would it help maintenance by moving to TS?

If all positive:

* Who can volunteer to help?

**Comment by markvincze** [comment]
In short: I'd absolutely support it.

Pros:
 - Makes code more reliable, the static compilation is a first safety net before unit tests are run.
 - Type definition files don't have to be maintained manually.  
(And maybe the structured comments are also better picked up by the tooling this way? I'm not sure)
 - It's easier to jump in development and discover what certain types/functions can do due to the type system holding our hands.

Cons:
 - Some TypeScript knowledge will be needed to do development on frint, this might discourage people who don't know or like it.  
(On the other hand it might make frint more interesting for TypeScript-fans :slightly_smiling_face:) 
 - Maybe the webpack/lerna/etc. config has to become more complicated?

I'd be happy to help, but can't make promises, I'm not sure how much free time I'll have :/.

**Comment by asci** [comment]
Any particular way you want to write it (like C#ish way or more Flow-ish)?

We have an experience using TypeScript in our projects and what I see so far — it really matters which features will you use. Sometimes doesn't look like JS and new concepts could lead to some new issues.

Also, tooling is matter — to get most of the typescript is it better to use VSCode\Webstorm. But there still could be some problems: for example, we found an issue with tslint using async\await. 

So for me would be cool to see the way you want to use it (like a guide or so)

**Comment by discosultan** [comment]
Overall I favor the idea and I think it makes sense since we already support TypeScript through type definition files.

Pros:

- It is easy to forget to update type definitions. Confusing consumers with stale definitions is worse than not having them at all. With source being in TypeScript, we lose this problem completely.
- Very nice development experience for newcomers. Editors such as VS Code can provide excellent 
autocompletion, navigation and refactoring support.
- Less bugs due to checking a large set of problems at transpile time as opposed to runtime.

Cons:

- The source code becomes a lot more verbose.
- Requires additional TypeScript tooling to be setup. No everyone is a fan of TypeScript and some external contributors may be turned off by this.

**Comment by fahad19** [comment]
Refs #406

**Comment by fahad19** [comment]
Yes, we are migrating.
